const jokeList = [
  "I got fired from a florist, apparently I took too many leaves. 😝",
  "How come the stadium got hot after the game? Because all of the fans left.",
  "What do you call a dictionary on drugs? High definition. 😲",
  "I'm tired of following my dreams. I'm just going to ask them where they are going and meet up with them later.",
  "Why did Mozart kill all his chickens? Because when he asked them who the best composer was, they'd all say 'Bach bach bach!'",
  "Why do fish live in salt water? Because pepper makes them sneeze!",
  "I went on a date last night with a girl from the zoo. It was great. She’s a keeper.",
  "What does a female snake use for support? A co-Bra!",
  "Today a man knocked on my door and asked for a small donation towards the local swimming pool. I gave him a glass of water.",
  "What's blue and not very heavy? Light blue.",
  "Did you hear the one about the guy with the broken hearing aid? Neither did he. ",
  "What do you call a fly without wings? A walk.",
  "When my wife told me to stop impersonating a flamingo, I had to put my foot down.",
  "What do you call someone with no nose? Nobody knows.",
  "What time did the man go to the dentist? Tooth hurt-y.",
  "Why can’t you hear a pterodactyl go to the bathroom? The p is silent.",
  "How many optometrists does it take to change a light bulb? 1 or 2? 1... or 2?",
  "I was thinking about moving to Moscow but there is no point Russian into things.",
  "Why does Waldo only wear stripes? Because he doesn't want to be spotted.",
  "Do you know where you can get chicken broth in bulk? The stock market.",
  "I used to work for a soft drink can crusher. It was soda pressing.",
  "A ghost walks into a bar and asks for a glass of vodka but the bar tender says, 'sorry we don’t serve spirits'",
  "I went to the zoo the other day, there was only one dog in it. It was a shitzu.",
  "I gave all my dead batteries away today, free of charge.",
  "Why are skeletons so calm? Because nothing gets under their skin.",
  "There’s a new type of broom out, it’s sweeping the nation.",
  "Why don’t seagulls fly over the bay? Because then they’d be bay-gulls!",
  "What did celery say when he broke up with his girlfriend? She wasn't right for me, so I really don't carrot all.",
  "What's the worst thing about ancient history class? The teachers tend to Babylon.",
  "What’s the difference between an African elephant and an Indian elephant? About 5000 miles.",
  "Why do scuba divers fall backwards into the water? Because if they fell forwards they’d still be in the boat.",
  "A weasel walks into a bar. The bartender says, 'Wow, I've never served a weasel before. What can I get for you?' 'Pop,' goes the weasel.",
  "Why do pirates not know the alphabet? They always get stuck at 'C'.",
];

export default jokeList;
